### ISSUE TITLE
Align Zeitaku logo to the center

### ISSUE THREAD

**Issue by Evavic44** [Evavic44/Hotel-Zeitaku#17]
The Zeitaku logo is slightly to the right of the container. See if you can align it to the center. 
### PS: This Property
```css
.logo {
    text-align: center;
}
```
### Wont work!! 🙃
